# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.meta.outputs.tags }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./app/HabitTracker
      - name: Build
        run: dotnet build ./app/HabitTracker --no-restore
      - name: Test
        run: dotnet test --verbosity normal ./tests/HabitTracker.UnitTests
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pillaru/habit-tracker
          tags: type=sha
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "remote deploy using SSH"
        uses: appleboy/ssh-action@v0.1.8
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE: ${{ needs.build.outputs.image_name }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          envs: DOCKER_USERNAME,DOCKER_PASSWORD,IMAGE
          script: |
            docker container stop habits
            docker container prune --force
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ghcr.io
            docker run --detach --name habits \
              --label "traefik.http.routers.habits-secure.rule=Host(\`habits.chekkan.com\`)" \
              --label "traefik.http.routers.habits-secure.tls=true" \
              --label "traefik.http.routers.habits-secure.tls.certresolver=myresolver" \
              --label "traefik.http.routers.habits.rule=Host(\`habits.chekkan.com\`)" \
              $IMAGE
